### PR TITLE
feat: mostly INVITE and KICK implementation and partially JOIN implementation

### LINKED ISSUE #9: Implement KICK command

### LINKED ISSUE #14: Implement INVITE command

### PR DESCRIPTION
**Pull request by ygor-sena**
This big PR adds a lot of things and observations to keep in mind:

- There are unit tests for USER and NICK commands. For each of them, a test fails and I'm not sure why. The failing tests are commented for later group review. To run the tests, go to `/tests` folder and run either `make user`or `make nick`;
- KICK is mostly implemented, with accompanying unit tests to validate the implementation. To run the tests, just `make kick`. #9
- INVITE is mostly implemented with accompanying unit tests to validate the implementation. To run the tests, just `make invite`. #14
- started PRIVMSG implementation, its parser function was created;
- standardized indentation to tabs.

### CODE REVIEW

**Review by carlosrocha-dev — APPROVED** [review]
Sounds to good

**Review by carlosrocha-dev — APPROVED** [review]
ok

**Comment by gialexan** [comment]
LGTM!

**Review by gialexan — APPROVED** [review]
Ok.

**Pull request merged**
